#!/usr/bin/env python3

from os.path import isdir, isfile
import requests
import re
import sys
import os


class Media:
    def __init__(self, tmdb_api_key, dest_path, files):
        self.dest_path = dest_path
        self.files = files
        self.tmdb_url = "https://api.themoviedb.org/3"
        self.tmdb_api_key = tmdb_api_key
        self.cache = {}

    def ask_to_select(self, orig_filename, selection_options):
        """Interface to select from search options"""

        print(orig_filename)
        print("\n".join(selection_options))

        try:
            selection = int(input("\nSelect option using num: "))
        except KeyboardInterrupt:
            exit(0)

        if selection < 1 or selection > len(selection_options):
            print("Index out of range...")
            exit(1)

        return int(selection) - 1

    def confirm_and_exec(self, rename_data):
        if not rename_data:
            return

        print("\n".join(f"{old} -> {new}" for old, new in rename_data))

        try:
            selection = input("\nDo you want to proceed?: ")
        except KeyboardInterrupt:
            exit(0)

        if selection == "y":
            for old, new in rename_data:
                os.makedirs(os.path.dirname(new), exist_ok=True)
                os.rename(old, new)

    def rename(self):
        pass


class Tv(Media):
    def __init__(self, tmdb_api_key, dest_path, files):
        super().__init__(tmdb_api_key, dest_path, files)

    def get_details(self, orig_filename, show_name):
        """Returns TMDB ID, Name of Show and Release Year"""
        url = f"{self.tmdb_url}/search/tv"
        res = requests.get(
            url, params={"api_key": self.tmdb_api_key, "query": show_name}
        )
        res.raise_for_status()
        res = res.json()["results"]

        if not res:
            new_show_name = " ".join(show_name.split()[:-1])
            if new_show_name:
                return self.get_details(orig_filename, new_show_name)

        if len(res) == 1:
            res = res[0]
        else:
            selection_options = [
                f"{i+1} {item.get('name')} ({item.get('first_air_date')}) [{item.get('id')}]"
                for i, item in enumerate(res)
            ]
            selection = self.ask_to_select(orig_filename, selection_options)
            res = res[selection]

        details = (
            res.get("id"),
            res.get("name"),
            res.get("first_air_date").split("-")[0],
        )

        return details

    def get_season_and_episode(self, file):
        """Returns season and episode number"""
        res = re.findall(r"s\d{1,2}e\d{1,2}", file.lower())
        if not res:
            return

        season, episode = re.findall(r"\d{1,2}", res[0])
        return season, episode

    def extract_show(self, path):
        """Extracts TV show name from file name"""
        path = re.sub(r"\W+", " ", path.lower())
        res = re.split(r"s\d{1,2}e\d{1,2}", path)

        return res[0].strip()

    def rename(self):
        rename_data = []
        for file in self.files:
            base_path = os.path.basename(file)

            show_name = self.extract_show(base_path)
            if not show_name:
                continue
            # print(f"{show_name=}")

            show_details = None
            if self.cache.get(show_name):
                show_details = self.cache.get(show_name)
            else:
                show_details = self.get_details(base_path, show_name)
                self.cache[show_name] = show_details

            if not show_details:
                continue
            tmdb_id, tmdb_name, tmdb_year = show_details
            # print(f"{tmdb_id=}, {tmdb_name=}, {tmdb_year=}")

            se = self.get_season_and_episode(file)
            if not se:
                continue

            season, episode = se
            # print(f"{season=}, {episode=}")

            new_path = os.path.join(
                self.dest_path,
                f"{tmdb_name} ({tmdb_year})",
                f"Season {season}",
                base_path,
            )
            rename_data.append((file, new_path))

        self.confirm_and_exec(rename_data)



if __name__ == "__main__":
    tmdb_api_key = os.getenv("TMDB_API_KEY")
    if not tmdb_api_key:
        print("Please export TMDB_API_KEY")
        exit(1)

    if len(sys.argv) < 4:
        print("Usage: python3 renamer.py <tv|mov> <dest_path> <files>")
        exit(1)

    paths = []
    for path in sys.argv[3:]:
        if isdir(path):
            paths.extend(
                [os.path.join(r, file) for r, _, f in os.walk(path) for file in f]
            )
        elif isfile(path):
            paths.append(path)

    media = None
    if sys.argv[1] == "tv":
        media = Tv(tmdb_api_key, sys.argv[2], paths)

    if not media:
        print("Invalid media type")
        exit(1)

    media.rename()
